#!/bin/bash

### COMP-5710 Final Project ###
### 5a - Create a Git Hook that will run and report all security weaknesses in the project in a CSV file whenever a Python file is changed and committed. (20%)

REPORT="security_vulnerability_report.csv"

TEMP=$(mktemp)

# Gets the list of all staged Python files if there are any (should be).
git diff --cached --name-only --diff-filter=ACM | grep '\.py$' > "$TEMP"

# Check if there are any Python files to scan
if [ -s "$TEMP" ]; then
    echo "Security scan running."

    echo "filename,line_number,issue,severity" > "$REPORT"

    # Runs Bandit on each staged Python file, and then appends the results to the REPORT.
    while IFS= read -r file
    do
        if [ -f "$file" ]; then
            bandit -f csv -o temp_sec.csv "$file"
            tail -n +2 temp_sec.csv >> "$REPORT"
        fi
    done < "$TEMP"

    rm temp_sec.csv

    if [ $(wc -l < "$REPORT") -gt 1 ]; then
        echo "Security issues detected by Bandit. See $REPORT for details."
    else
        echo "No security issues found by Bandit."
        rm "$REPORT"
    fi
else
    echo "No Python files staged for commit. Skipping Bandit scan."
fi

rm "$TEMP"

exit 0